### ISSUE TITLE
KSENIA40 - Integration crash for missing system temperature value 

### ISSUE THREAD

**Issue by Trexano99** [sdomotica/hassio-addons#13]
I am using the Sdomotica Ksenia 4.0 add-on and it works amazing!
Anyway is not the first time that i got a crash of the system due to `nan` value propagated for temperature from the central.
I know this is a log error from MQTT, but i think is fully related with the add-on and not whit the MQTT reliability.
Is this a problem to be fixed or am I missing something?

Leave down here the logs propagated from the Home Assistant logs:

```
Registratore: homeassistant.components.mqtt.models
Fonte: components/mqtt/models.py:366
Integrazione: MQTT ([documentazione](https://www.home-assistant.io/integrations/mqtt), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
Prima occorrenza: 26 dicembre 2024 alle ore 12:12:33 (1 occorrenze)
Ultimo accesso: 26 dicembre 2024 alle ore 12:12:33

Exception raised while updating state of sensor.sdomotica401, topic: 'sdomotica40/system/status/1/temp/in' with payload: b'NaN'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 366, in process_write_state_requests
    entity.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 690, in state
    raise ValueError(
    ...<5 lines>...
    )
ValueError: Sensor sensor.sdomotica401 has device class 'temperature', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-finite value: 'nan'
```
P.S: The `sensor.sdomotica401` wich seems to cause the error has state `unknown` even when the add-on and the system is fully working.

Thanks in advance!

**Comment by sdomotica** [comment]
Go on the sdomotica40.yaml package and comment or delete the sensor.
This error don't crash HA, but maybe that you don't have termal sensor con central unit
Reload the configuration and delete the entity sensor

![immagine](https://github.com/user-attachments/assets/f18ddf53-01a3-4f7d-be4b-35b3dd9b8141)
